/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_domzi_mt2_NativeInterface */

#ifndef _Included_com_domzi_mt2_NativeInterface
#define _Included_com_domzi_mt2_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_domzi_mt2_NativeInterface_init
  (JNIEnv *, jobject);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    captureImage
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_captureImage
  (JNIEnv *, jobject);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    registerArea
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_registerArea
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    setDiceRoi
 * Signature: ([F)I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_setDiceRoi
  (JNIEnv *, jobject, jfloatArray);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    registerRemote
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_registerRemote
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    getRemote
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_getRemote
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    registerFigure
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_registerFigure
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    getFigure
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_getFigure
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    getDice
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_getDice
  (JNIEnv *, jobject);

/*
 * Class:     com_domzi_mt2_NativeInterface
 * Method:    getEyes
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_domzi_mt2_NativeInterface_getEyes
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
